title: Matt Himrod
author:
  name: Matt Himrod

description: >
  This is my personal website.

url: "https://matthimrod.com"
baseurl: "https://matthimrod.com"
repository: "matthimrodtest/matthimrod.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.28.1"

minimal_mistakes_skin: "dark"
include: ["_pages"]

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

enable_copy_code_button: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author: Matt Himrod
      author_profile: true
      toc: false
  - scope:
      path: ""
      type: posts
    values:
      layout: posts
      author: Matt Himrod
      author_profile: true
      show_date: true
      toc: false
