title: Matt Himrod
author: Matt Himrod

description: >
  This is my personal website.

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
include: ["_pages"]

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - resume.md

show_excerpts: true
enable_copy_code_button: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author: Matt Himrod
      author_profile: true
      toc: false
  - scope:
      path: ""
      type: posts
    values:
      layout: posts
      author: Matt Himrod
      author_profile: true
      show_date: true
      toc: false
#      sidebar:
#        nav: "side"
